# permissions for end users to view etcddumps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcddump-viewer-role
rules:
- apiGroups:
  - app.etcdCluster.cn
  resources:
  - etcddumps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.etcdCluster.cn
  resources:
  - etcddumps/status
  verbs:
  - get
