# permissions for end users to view etcdrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdrestore-viewer-role
rules:
- apiGroups:
  - app.etcdCluster.cn
  resources:
  - etcdrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.etcdCluster.cn
  resources:
  - etcdrestores/status
  verbs:
  - get
